# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "72caa794d011b6f2f913956aef44ef66"
name = "render-sample-app"
handle = "render-sample-app-1"
application_url = "https://italy-prove-albany-madrid.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://italy-prove-albany-madrid.trycloudflare.com/auth/callback",
  "https://italy-prove-albany-madrid.trycloudflare.com/auth/shopify/callback",
  "https://italy-prove-albany-madrid.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
